/** Demo data for VoltPath Shield — Women Safety Mode (UI). */

export const SHIELD_STATIONS = [
  {
    id: '1',
    name: 'Aurora Superhub · Bayfront',
    distanceKm: 2.1,
    chargerType: 'DC 150kW',
    available: true,
    ports: '3 / 6',
    safetyRating: 4.9,
    cctv: true,
    open247: true,
    crowd: 'Moderate',
    waitMin: 8,
    womenSafe: true,
    fast: true,
  },
  {
    id: '2',
    name: 'Lumen Plaza EV',
    distanceKm: 4.6,
    chargerType: 'DC 50kW',
    available: true,
    ports: '1 / 4',
    safetyRating: 4.6,
    cctv: true,
    open247: false,
    crowd: 'Busy',
    waitMin: 22,
    womenSafe: true,
    fast: false,
  },
  {
    id: '3',
    name: 'Harbor Line Hub',
    distanceKm: 6.2,
    chargerType: 'DC 350kW',
    available: false,
    ports: '0 / 8',
    safetyRating: 4.8,
    cctv: true,
    open247: true,
    crowd: 'High',
    waitMin: 35,
    womenSafe: true,
    fast: true,
  },
  {
    id: '4',
    name: 'Riverside Quick',
    distanceKm: 8.0,
    chargerType: 'AC 22kW',
    available: true,
    ports: '2 / 2',
    safetyRating: 3.9,
    cctv: false,
    open247: false,
    crowd: 'Low',
    waitMin: 0,
    womenSafe: false,
    fast: false,
  },
];

export const COMMUNITY_REVIEWS = [
  {
    id: 'r1',
    author: 'Priya · verified',
    station: 'Aurora Superhub',
    rating: 5,
    text: 'Well-lit lot, security visible. Felt safe charging alone at 11pm.',
    trust: 'High trust',
  },
  {
    id: 'r2',
    author: 'Ananya',
    station: 'Lumen Plaza',
    rating: 4,
    text: 'Busy mall area — good foot traffic.',
    trust: 'Verified',
  },
];

export const NEARBY_EMERGENCY = [
  { type: 'Police', label: 'Central Precinct', dist: '1.2 km' },
  { type: 'Hospital', label: 'City General ER', dist: '2.4 km' },
  { type: 'Hotel', label: 'Marina Inn (24h)', dist: '0.8 km' },
  { type: 'Public', label: 'Transit hub', dist: '0.5 km' },
];
